name: Build

on:
  release:
    types: [published]
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        java: ['11', '17']
        scala: ['2.12.10']
    steps:
    - name: Debug info
      run: echo ref:${{github.ref}}
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'sbt'
    - uses: coursier/cache-action@v6
      with:
        extraKey: scala-${{ matrix.scala }}
    - name: Compile & Test
      run: sbt checkAll
